/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alfray_mandelbrot_NativeMandel */

#ifndef _Included_com_alfray_mandelbrot_NativeMandel
#define _Included_com_alfray_mandelbrot_NativeMandel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alfray_mandelbrot_NativeMandel
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_alfray_mandelbrot_NativeMandel_add
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
