/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alfray_mandelbrot_NativeMandel */

#ifndef _Included_com_alfray_mandelbrot_NativeMandel
#define _Included_com_alfray_mandelbrot_NativeMandel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alfray_mandelbrot_NativeMandel
 * Method:    native_mandelbrot
 * Signature: (FFFII[II)I
 */
JNIEXPORT jint JNICALL Java_com_alfray_mandelbrot_NativeMandel_native_1mandelbrot
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
